version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "area/dependency"
      - "release-note-none"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"